export interface BulkOrderModel {
  saleChannel: string;
  saleId: string;
  gatewayId: string;
  businessId: string;
  businessName: null;
  gatewayName: null;
  uniqueCode: string;
  firstName: string;
  lastName: string;
  name: string;
  nationalCode: string;
  mobile: string;
  productId: string;
  productName: string;
  productCategory: string;
  productBrand: string;
  productModel: string;
  productPrice: number;
  payableAmount: null;
  serialNumber: null | string;
  sendSmsAt: Date | null;
  remainingPayDays: number | null;
  currentState: number;
  isPayable: boolean;
  notPayableReason: string | null;
  providerId: null;
  policyNumber: string;
  canSendLeadSms: null;
  hasClaim?: boolean;
  canBeExtended: null;
  canSendIssueSms: null;
  discountCode: null;
  calculationType: null;
  discountAmount: number | null;
  maxApplyAmount: number | null;
  discountUsableFrom: null;
  discountUsableTo: null;
  discountReservedAt: null;
  orderCreatedAt: Date;
  paymentIsSucceed: boolean;
  resendSms: string;
  verifyPaymentGateway: null;
  state: string;
  link: string;
}
