import { BeforeLoginRouteModel } from './before-login-route.model';
import { SubscriptionSchemaModel } from './subscription-schema.model';
import { ForgetPasswordSchemaModel } from './forget-password-schema.model';
import { Coordination } from '@client-monorepo/common/location-management';
import { FrequentServicesIdEnum } from '@client-monorepo/common/service-data';
import { InputUtmData } from './input-utm-data';
import { AuthResponse } from '@client-monorepo/common/user';

export interface IStorageService {
  getUserId(): string;
  setUserData(data: { userId: string; phoneNumber: string }): void;
  getUserData(): any;
  getRefreshToken(): string | null;
  getToken(): string | null;
  isLoggedIn(): boolean;
  isTokenExpired(): boolean;
  storeBeforeLoginRoute(route: BeforeLoginRouteModel): void;
  getBeforeLoginRoute(): BeforeLoginRouteModel | null;
  storeOnBoardingChecked(): void;
  isOnboardingChecked(): boolean;
  setWalkThroughSate(rootElementId: string, step: string): void;
  getWalkThroughSate(rootElementId: string): string | null;
  updateAuth(response: AuthResponse): void;
  expireToken(): void;
  setCardHistory(srcCardIndex: number | string, data: any): void;
  getCardHistory(): any;
  removeCardHistory(cardIndex: PropertyKey): void;
  getSubscriptionStorage(): SubscriptionSchemaModel;
  setSubscriptionStorage(subscriptionParams: SubscriptionSchemaModel): void;
  removeSubscriptionStorage(): void;
  getForgetPasswordStorage(): ForgetPasswordSchemaModel;
  setForgetPasswordStorage(forgetPasswordParams: ForgetPasswordSchemaModel): void;
  removeForgetPasswordStorage(): void;
  getRedirectUrlAfterLogin(): string | null;
  removeRedirectUrlAfterLogin(): void;
  setPassword(): void;
  isSetPassword(): boolean;
  removePasswordData(): void;
  getCallbackUrl(): string | null;
  saveCallbackUrl(value: string): void;
  setTicketData(ticket: string, data: any): void;
  getTicketData(): any;
  removeTicketData(ticket: PropertyKey): void;
  addResolveUrl(url: string): void;
  setHasBiometric(): void;
  hasBiometric(): boolean;
  removeHasBiometric(): void;
  getSearchHistory(): Array<string>;
  setSearchHistory(history: Array<string>): void;
  getHubSearchHistory(): Array<FrequentServicesIdEnum>;
  setHubSearchHistory(history: Array<FrequentServicesIdEnum>): void;
  removeHubSearchHistory(): void;
  setTimeStamp(time: number): void;
  getTimeStamp(): string | null;
  removeTimeStamp(): void;
  setRedirectionTimestamp(time: number): void;
  getRedirectionTimestamp(): string | null;
  removeRedirectionTimestamp(): void;
  getLocationTimeStamp(): number | null;
  setLocationTimeStamp(timestamp: number): void;
  removeLocationTimeStamp(): void;
  getNativeUpdateTimeStamp(): number | null;
  setNativeUpdateTimeStamp(timestamp: number): void;
  removeNativeUpdateTimeStamp(): void;
  setHasLocation(): void;
  hasSetLocation(): boolean;
  removeSetLocation(): void;
  getLastLocation(): Coordination | undefined;
  setLastLocation(location: Coordination): void;
  removeLastLocation(): void;
  getLocationEventTimeStamp(): number | null;
  setLocationEventTimeStamp(timestamp: number): void;
  removeLocationEventTimeStamp(): void;
  setInputUtmData(utmData: InputUtmData): void;
  getInputUtmData(): null | InputUtmData;
  getSessionId(): string;
  setCheckHubOnboarding(): void;
  hasCheckHubOnboarding(): boolean;
  storeDigipayCardOnboardingChecked(): void;
  isDigipayCardOnboardingChecked(): boolean;
  toggleAssetHide(key: string): boolean;
  getAssetsHideStatus(): any;
  resetAssetHideStatus(): void;
  setMessageApiCall(): void;
  isMessageApiCall(): boolean;
  getAppMessageTimeStamp(): number | null;
  setAppMessageTimeStamp(timestamp: number): void;
  removeAppMessageTimeStamp(): void;
}
