export const environment = {
  name: 'production',
  production: true,
  api_prefix: '/digipay/api',
  api_username: 'webapp-client-id',
  api_password: 'webapp-client-secret-debee79d-b04d-47ef-8ed5-c32e24ec836e',
  digipay_version: '2019-07-17',
  google_tag_manager_id: 'GTM-PS2XTV5J',
  google_analytics_tracking_id: 'UA-151185661-1',
  fail_url: 'https://www.digikala.com/',
  // prefix should not have trailing slash
  route_prefix: '/web-pay',
  app_base_url: 'https://web.mydigipay.com/web-pay',
  sentryDsn:'https://e56947a6fe484cfe8a442d80cb37f664@sentry.mydigipay.info/76',
  sentryTarget:['https://web.mydigipay.com/web-pay/tgs'],
  tracesSampleRate:0,
  sampleRate:0.1,
  android_agent: 'HYBRID_ANDROID',
  ios_agent: 'HYBRID_IOS',
  web_agent: 'WEB',
  web_username: 'webapp-client-id',
  web_password: 'webapp-client-secret-3cc0504a-76c5-488d-8f20-8b235126c5d0',
  android_hybrid_username: 'hybrid-android-client-id',
  android_hybrid_password: 'B5U4i7kzHWVcMCTitvcD',
  ios_hybrid_username: 'hybrid-ios-client-id',
  ios_hybrid_password: 'WtRP6H9n7pjH5QhY8YzK',
};
