import { FrequentServiceInterface } from '../models/frequent-service.interface';
import { FrequentServicesIdEnum } from '../models/frequent-services-id.enum';
import { ServiceImagesType } from '../models/service-images-type.enum';

export const frequentServices: Record<FrequentServicesIdEnum, FrequentServiceInterface> = {
  [FrequentServicesIdEnum.C2C]: {
    id: FrequentServicesIdEnum.C2C,
    icon: 'card-to-card',
    primaryColor: '#77A0FD',
    secondaryColor: '#2164FC',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.WALLET]: {
    id: FrequentServicesIdEnum.WALLET,
    icon: 'wallet-in',
    primaryColor: '#77A0FD',
    secondaryColor: '#2164FC',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.CREDIT]: {
    id: FrequentServicesIdEnum.CREDIT,
    icon: 'Credit',
    primaryColor: '#9E84EB',
    secondaryColor: '#6B47EB',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.BNPL]: {
    id: FrequentServicesIdEnum.BNPL,
    icon: 'bnpl',
    primaryColor: '#9E84EB',
    secondaryColor: '#6B47EB',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.TOPUP]: {
    id: FrequentServicesIdEnum.TOPUP,
    icon: 'simcard',
    primaryColor: '#FEB780',
    secondaryColor: '#FE8020',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.BUNDLE]: {
    id: FrequentServicesIdEnum.BUNDLE,
    icon: 'Network',
    primaryColor: '#FEB780',
    secondaryColor: '#FE8020',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.BILL]: {
    id: FrequentServicesIdEnum.BILL,
    icon: 'Receipt-bill',
    primaryColor: '#FEB780',
    secondaryColor: '#FE8020',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.CHARITY]: {
    id: FrequentServicesIdEnum.CHARITY,
    icon: 'heart',
    primaryColor: '#F7929A',
    secondaryColor: '#F03D4C',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.TRAFFIC_FINES]: {
    id: FrequentServicesIdEnum.TRAFFIC_FINES,
    icon: 'receipt-bill',
    primaryColor: '#81859C',
    secondaryColor: '#4C495F',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.TOLL]: {
    id: FrequentServicesIdEnum.TOLL,
    icon: 'highway',
    primaryColor: '#81859C',
    secondaryColor: '#4C495F',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.TAXI]: {
    id: FrequentServicesIdEnum.TAXI,
    icon: 'taxi-Car',
    primaryColor: '#FED080',
    secondaryColor: '#FEA034',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.WEALTH]: {
    id: FrequentServicesIdEnum.WEALTH,
    icon: 'bar-chart-upward',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.INSURANCE]: {
    id: FrequentServicesIdEnum.INSURANCE,
    icon: 'note-shield',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.BARCODE_SCANNER]: {
    id: FrequentServicesIdEnum.BARCODE_SCANNER,
    icon: 'scan',
    primaryColor: '#77A0FD',
    secondaryColor: '#2164FC',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.PAYMENT_OF_INSTALLMENT]: {
    id: FrequentServicesIdEnum.PAYMENT_OF_INSTALLMENT,
    icon: 'calendar-time',
    primaryColor: '#9E84EB',
    secondaryColor: '#6B47EB',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.INSTALLMENT_PURCHASE_WITH_CHECK]: {
    id: FrequentServicesIdEnum.INSTALLMENT_PURCHASE_WITH_CHECK,
    icon: 'document-copy',
    primaryColor: '#9E84EB',
    secondaryColor: '#6B47EB',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.MCI_MOBILE_BILL]: {
    id: FrequentServicesIdEnum.MCI_MOBILE_BILL,
    image: 'mci.svg',
    icon: 'mci.svg',
    selected: false,
    logoType: 'logo',
    imageType: ServiceImagesType.SRC,
  },
  [FrequentServicesIdEnum.MTN_MOBILE_BILL]: {
    id: FrequentServicesIdEnum.MTN_MOBILE_BILL,
    image: 'mtn.svg',
    icon: 'mtn.svg',
    selected: false,
    logoType: 'logo',
    imageType: ServiceImagesType.SRC,
  },
  [FrequentServicesIdEnum.RIGHTEL_MOBILE_BILL]: {
    id: FrequentServicesIdEnum.RIGHTEL_MOBILE_BILL,
    image: 'rightel.svg',
    icon: 'rightel.svg',
    selected: false,
    logoType: 'logo',
    imageType: ServiceImagesType.SRC,
  },
  [FrequentServicesIdEnum.INVESTMENT_FUNDS]: {
    id: FrequentServicesIdEnum.INVESTMENT_FUNDS,
    icon: 'Chart-three-line',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  // [FrequentServicesIdEnum.GOLD_FUNDS]: {
  //   id: FrequentServicesIdEnum.GOLD_FUNDS,
  //   icon: 'gold-Bag',
  //   primaryColor: '#9CE5A7',
  //   secondaryColor: '#2FBE72',
  //   selected: false,
  //   logoType: 'icon',
  //  imageType: ServiceImagesType.ICON,
  // },
  [FrequentServicesIdEnum.MOLTEN_GOLD_FUNDS]: {
    id: FrequentServicesIdEnum.MOLTEN_GOLD_FUNDS,
    icon: 'gold-bag',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.REAL_ESTATE_INVESTMENT]: {
    id: FrequentServicesIdEnum.REAL_ESTATE_INVESTMENT,
    icon: 'Chart-three-line',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.CROWDFUNDING]: {
    id: FrequentServicesIdEnum.CROWDFUNDING,
    icon: 'Compound',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.CAR_BODY_INSURANCE]: {
    id: FrequentServicesIdEnum.CAR_BODY_INSURANCE,
    icon: 'car-crash',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.THIRD_PARTY_INSURANCE]: {
    id: FrequentServicesIdEnum.THIRD_PARTY_INSURANCE,
    icon: 'car-2',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.ELECTRICAL_DEVICES_INSURANCE]: {
    id: FrequentServicesIdEnum.ELECTRICAL_DEVICES_INSURANCE,
    icon: 'digital-device',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.WEALTH_WALLET]: {
    id: FrequentServicesIdEnum.WEALTH_WALLET,
    icon: 'bag-of-wealth',
    primaryColor: '#9CE5A7',
    secondaryColor: '#2FBE72',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.INSURANCE_HOME]: {
    id: FrequentServicesIdEnum.INSURANCE_HOME,
    icon: 'building',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.TAPSI]: {
    id: FrequentServicesIdEnum.TAPSI,
    icon: 'tapsi',
    primaryColor: '#5667D3',
    secondaryColor: '#3747B4',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
  [FrequentServicesIdEnum.THIRD_PARTY_MOTOR]: {
    id: FrequentServicesIdEnum.THIRD_PARTY_MOTOR,
    icon: 'motor',
    primaryColor: '#7883D3',
    secondaryColor: '#3E4AA3',
    selected: false,
    logoType: 'icon',
    imageType: ServiceImagesType.ICON,
  },
};
