export enum CONTRACT_DEBT_STATUS {
  DUE,
  SETTLED,
  CURRENT,
  UNPAYABLE,
}

export const CONTRACT_DEBT_STATUS_CARD_CLASS = {
  [CONTRACT_DEBT_STATUS.DUE]: 'active',
  [CONTRACT_DEBT_STATUS.SETTLED]: 'disabled',
  [CONTRACT_DEBT_STATUS.CURRENT]: 'info',
  [CONTRACT_DEBT_STATUS.UNPAYABLE]: 'disabled',
};

export const CONTRACT_DEBT_STATUS_TRANSLATION = {
  [CONTRACT_DEBT_STATUS.DUE]: 'سررسید شده',
  [CONTRACT_DEBT_STATUS.SETTLED]: 'تسویه شده',
  [CONTRACT_DEBT_STATUS.CURRENT]: 'باقی‌مانده',
  [CONTRACT_DEBT_STATUS.UNPAYABLE]: 'باقی‌مانده',
};
