import { VehiclePlateDetails } from '../../../../../api/digipay/models/driving-fine/vehicle-plate';

export const plateDetails: VehiclePlateDetails[] = [
  {
    title: 'الف',
    code: '01',
    imageId: 'plate.01',
    color: 'CD292A',
    fontColor: 'ffffff',
  },
  {
    title: 'ب',
    code: '02',
    imageId: 'plate.02',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'پ',
    code: '03',
    imageId: 'plate.03',
    color: '0C4D37',
    fontColor: 'ffffff',
  },
  {
    title: 'ت',
    code: '04',
    imageId: 'plate.04',
    color: 'FEC619',
    fontColor: '000000',
  },
  {
    title: 'ث',
    code: '05',
    imageId: 'plate.05',
    color: '0C4D37',
    fontColor: 'ffffff',
  },
  {
    title: 'ج',
    code: '06',
    imageId: 'plate.06',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'د',
    code: '10',
    imageId: 'plate.10',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ز',
    code: '13',
    imageId: 'plate.13',
    color: '004E99',
    fontColor: 'ffffff',
  },
  {
    title: 'س',
    code: '15',
    imageId: 'plate.15',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ش',
    code: '16',
    imageId: 'plate.16',
    color: 'DAC08D',
    fontColor: '000000',
  },
  {
    title: 'ص',
    code: '17',
    imageId: 'plate.17',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ط',
    code: '19',
    imageId: 'plate.19',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ع',
    code: '21',
    imageId: 'plate.21',
    color: 'FEC619',
    fontColor: '000000',
  },
  {
    title: 'ف',
    code: '23',
    imageId: 'plate.23',
    color: '004E99',
    fontColor: 'ffffff',
  },
  {
    title: 'ق',
    code: '24',
    imageId: 'plate.24',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ک',
    code: '25',
    imageId: 'plate.25',
    color: 'FEC619',
    fontColor: '000000',
  },
  {
    title: 'گ',
    code: '26',
    imageId: 'plate.26',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ل',
    code: '27',
    imageId: 'plate.27',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'م',
    code: '28',
    imageId: 'plate.28',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ن',
    code: '29',
    imageId: 'plate.29',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'و',
    code: '30',
    imageId: 'plate.30',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ه',
    code: '31',
    imageId: 'plate.31',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'ي',
    code: '32',
    imageId: 'plate.32',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'معلولین',
    code: '33',
    imageId: 'plate.33',
    color: 'ffffff',
    fontColor: '000000',
  },
  {
    title: 'D',
    code: '54',
    imageId: 'plate.54',
    color: '148FCB',
    fontColor: '000000',
  },
  {
    title: 'S',
    code: '69',
    imageId: 'plate.69',
    color: '148FCB',
    fontColor: '000000',
  },
];
