export enum EsLoanSendEmailStateEnum {
  PROVIDER_VERIFICATION_COMPLETED = 'PROVIDER_VERIFICATION_COMPLETED',
  ES_LOAN_CHEQUE_GUIDELINE_SENT = 'ES_LOAN_CHEQUE_GUIDELINE_SENT',
  ES_LOAN_CHEQUE_IMAGE_RECEIVED = 'ES_LOAN_CHEQUE_IMAGE_RECEIVED',
  ES_LOAN_CHEQUE_APPROVED = 'ES_LOAN_CHEQUE_APPROVED',
  ES_LOAN_CHEQUE_REJECTED = 'ES_LOAN_CHEQUE_REJECTED'
}
