import { environment } from '../../../environments/environment';

export const API_CONSTANTS = {
  HTTP_AGENT: 'WEB',
  USER_NAME: environment.api_username,
  USER_KEY: environment.api_password,
  DIGIPAY_VERSION: environment.digipay_version,
};

export const BASIC_AUTH_HEADER = 'Basic ' + btoa(API_CONSTANTS.USER_NAME + ':' + API_CONSTANTS.USER_KEY);

export const FEATURE_NAMES = {
  PAYMENT_WALLET: 'PAYMENT_WALLET',
  PAYMENT_DPG: 'PAYMENT_DPG',
  PAYMENT_IPG: 'PAYMENT_IPG',
  SETTINGS: 'SETTINGS',
  SETTINGS_PASSWORD: 'SETTINGS_PASSWORD',
  LOGIN_HOME: 'LOGIN_HOME',
  SDK_INFO: 'SDK_INFO',
  NAV_HOME: 'NAV_HOME',
  NAV_TRANSACTIONS: 'NAV_TRANSACTIONS',
  NAV_BARCODE_READER: 'NAV_BARCODE_READER',
  NAV_FESTIVAL: 'NAV_FESTIVAL',
  SETTINGS_REFERRAL: 'SETTINGS_REFERRAL',
  SETTINGS_C2C_MANAGEMENT: 'SETTINGS_C2C_MANAGEMENT',
  SETTINGS_TERMS: 'SETTINGS_TERMS',
  SETTINGS_ABOUT_US: 'SETTINGS_ABOUT_US',
  SETTINGS_FEEDBACK: 'SETTINGS_FEEDBACK',
  SETTINGS_HELP: 'SETTINGS_HELP',
  SETTINGS_PROFILE: 'SETTINGS_PROFILE',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
};

export const FEATURES = {
  [FEATURE_NAMES.PAYMENT_WALLET]: 0,
  [FEATURE_NAMES.PAYMENT_DPG]: 1,
  [FEATURE_NAMES.PAYMENT_IPG]: 2,
  [FEATURE_NAMES.SETTINGS]: 50,
  [FEATURE_NAMES.SETTINGS_PASSWORD]: 51,
  [FEATURE_NAMES.LOGIN_HOME]: 100,
  [FEATURE_NAMES.SDK_INFO]: 150,
  [FEATURE_NAMES.NAV_HOME]: 200,
  [FEATURE_NAMES.NAV_TRANSACTIONS]: 201,
  [FEATURE_NAMES.NAV_BARCODE_READER]: 202,
  [FEATURE_NAMES.NAV_FESTIVAL]: 203,
  [FEATURE_NAMES.SETTINGS_REFERRAL]: 52,
  [FEATURE_NAMES.SETTINGS_C2C_MANAGEMENT]: 53,
  [FEATURE_NAMES.SETTINGS_TERMS]: 54,
  [FEATURE_NAMES.SETTINGS_ABOUT_US]: 55,
  [FEATURE_NAMES.SETTINGS_FEEDBACK]: 56,
  [FEATURE_NAMES.SETTINGS_HELP]: 57,
  [FEATURE_NAMES.SETTINGS_PROFILE]: 58,
  [FEATURE_NAMES.SETTINGS_UPDATE]: 59,
};

export enum PROTECTIONS {
  NONE = 0,
  PIN = 1,
  OTP = 2,
  IN_APP_VERIFICATION = 3
}

export const PAYMENT_GATEWAYS = {
  IPG: 0,
  DPG: 1,
  WALLET: 3,
  CPG: 4,
  // Reverse
  0: 'IPG',
  1: 'DPG',
  3: 'WALLET',
  4: 'CPG',
};

export const PAYMENT_GATEWAYS_TRANSLATE = {
  IPG: 'پرداخت آنلاین',
  WALLET: 'پرداخت با کیف پول دیجی‌پی',
  CPG: 'خرید اعتباری',
  // Reverse
  2: 'پرداخت آنلاین',
  0: 'پرداخت با کیف پول دیجی‌پی',
  1: 'خرید اعتباری',
};

export const GATEWAY_TO_FEATURE_MAP = {
  WALLET: FEATURES[FEATURE_NAMES.PAYMENT_WALLET],
  IPG: FEATURES[FEATURE_NAMES.PAYMENT_IPG],
  DPG: FEATURES[FEATURE_NAMES.PAYMENT_DPG],
  // Reverse
  3: FEATURE_NAMES.PAYMENT_WALLET,
  0: FEATURE_NAMES.PAYMENT_IPG,
  1: FEATURE_NAMES.PAYMENT_DPG
};
