export enum InternetPackageDurations {
  MONTHLY = 1,
  TRIMESTER = 2,
  SEMI_ANNUAL = 3,
  ANNUAL = 4,
  WEEKLY = 5,
  HOURLY = 6,
  DAILY = 7,
  THREE_DAYS = 8,
  FIFTEEN_DAYS = 9,
  TWENTY_DAYS = 10,
  TEN_DAYS = 11,
  FIVE_DAYS = 12,
  NIGHTLY = 13,
  OTHER = 14,
  BI_MONTHLY = 15,
  QUAD_MONTHLY = 16,
}

export const INTERNET_PACKAGE_DURATIONS_TRANSLATIONS = {
  [InternetPackageDurations.MONTHLY]: '۱ ماهه',
  [InternetPackageDurations.TRIMESTER]: '۳ ماهه',
  [InternetPackageDurations.SEMI_ANNUAL]: '۶ ماهه',
  [InternetPackageDurations.ANNUAL]: 'سالانه',
  [InternetPackageDurations.WEEKLY]: 'هفتگی',
  [InternetPackageDurations.HOURLY]: 'ساعتی',
  [InternetPackageDurations.DAILY]: '۱ روزه',
  [InternetPackageDurations.THREE_DAYS]: '۳ روزه',
  [InternetPackageDurations.FIFTEEN_DAYS]: '۱۵ روزه',
  [InternetPackageDurations.TWENTY_DAYS]: '۲۰ روزه',
  [InternetPackageDurations.TEN_DAYS]: '۱۰ روزه',
  [InternetPackageDurations.FIVE_DAYS]: '۵ روزه',
  [InternetPackageDurations.NIGHTLY]: 'شبانه',
  [InternetPackageDurations.OTHER]: 'سایر',
  [InternetPackageDurations.BI_MONTHLY]: '۲ ماهه',
  [InternetPackageDurations.QUAD_MONTHLY]: '۴ ماهه',
};
