export enum GenerateDigitalSignatureStepStatus {
  INITIATED,
  IN_PROGRESS,
  READY_TO_GENERATION,
  COMPLETED,
  EXPIRED,
  ONBOARDED,
  REGISTERED,
  IMAGE_UPLOADED,
  SELFIE_UPLOADED,
  VIDEO_UPLOADED,
}
