export const environment = {
  env: 'local',
  app_url: 'http://localhost:4200/',
  base_url: '/digipay/api',
  base_url_origin: '',
  base_url_abs: '/digipay/api',
  base_url_origin_abs: '',
  developing_app_url: 'http://172.22.10.11:4200/',
  agents: {
    web_agent: 'WEB',
    android_agent: 'HYBRID_ANDROID',
    ios_agent: 'HYBRID_IOS',
  },
  client_ids: {
    web_username: 'escrow-client-id',
    android_hybrid_username: 'hybrid-android-client-id',
    ios_hybrid_username: 'hybrid-ios-client-id',
  },
  client_secrets: {
    web_password: 'escrow-client-secret-1556541',
    android_hybrid_password: 'B5U4i7kzHWVcMCTitvcD',
    ios_hybrid_password: 'WtRP6H9n7pjH5QhY8YzK',
  },
  intrack_config: {
    app_key: 'AAAAKQ',
    auth_key: 'e79aef46-1a9d-449c-a184-f5adbbab19f9',
    public_key: 'BGsjImFouv6gWBSqq8vGpz6nDg0q1KNA2G-HeLMBTF3njYDIugcV8C0c2WpB4HjFzlGi8mLaF2OuiOBXILINTT8=',
    android_auth_key: 'bf4bc749-e147-483c-bd0d-67e0f98f350d',
    ios_auth_key: 'b5183735-ecb0-4d64-9355-10530d3f79f3',
  },
  sentry_config: {
    dsn: 'https://201b09d1db7fe0be477d7130bcee87bb@crashlytics.mydigipay.com/114',
    target: ['https://uatplink.mydigipay.info'],
    tracesSampleRate: 1,
  },
  google_tag_manager_id: '',
  digipay_version: '2025-01-01',
  version_check_period_seconds: '180',
  merchant_registration_url: 'https://uatbusiness.mydigipay.info/auth/login',
};
