import { ListOptionEnum } from '../../../../data-access/enums/list-option.enum';
import { VEHICLE_BODY_POLICY_STATE_ENUM } from '../../../../data-access/enums/vehicle-body-policy-state.enum';

export const BIMEH_THIRD_PARTY_TYPE_STATE_MAP = {
  [ListOptionEnum.PURCHASED]: [
    VEHICLE_BODY_POLICY_STATE_ENUM.WAITINGFORADDRESSREGISTRATION,
    VEHICLE_BODY_POLICY_STATE_ENUM.REVIEWADDRESS,
    VEHICLE_BODY_POLICY_STATE_ENUM.REVIEWFAILEDADDRESS,
    VEHICLE_BODY_POLICY_STATE_ENUM.DEBTOR,
    VEHICLE_BODY_POLICY_STATE_ENUM.ISSUED,
    VEHICLE_BODY_POLICY_STATE_ENUM.VISITDOCUMENTDEFECT,
    VEHICLE_BODY_POLICY_STATE_ENUM.PENDING,
    VEHICLE_BODY_POLICY_STATE_ENUM.CANCELED,
    VEHICLE_BODY_POLICY_STATE_ENUM.REJECTED,
    VEHICLE_BODY_POLICY_STATE_ENUM.INQUIRY,
  ],
  [ListOptionEnum.RENEWAL]: [],
  [ListOptionEnum.UNCOMPLETE]: [
    VEHICLE_BODY_POLICY_STATE_ENUM.INQUIRY,
  ],
};
