import { ListOptionEnum } from '../../../../data-access/enums/list-option.enum';
import { VEHICLE_ORDER_STATE_ENUM } from '../../../../../../data-access/enums/vehicle-order-state.enum';

export const THIRD_PARTY_TYPE_STATE_MAP = {
  [ListOptionEnum.UNCOMPLETE]: [
    VEHICLE_ORDER_STATE_ENUM.DRAFT,
    VEHICLE_ORDER_STATE_ENUM.CHECKOUT,
    VEHICLE_ORDER_STATE_ENUM.PENDING_PAYMENT,
  ],
  [ListOptionEnum.PURCHASED]: [
    VEHICLE_ORDER_STATE_ENUM.PAID,
    VEHICLE_ORDER_STATE_ENUM.USER_INFO_COMPLETED,
    VEHICLE_ORDER_STATE_ENUM.DOCUMENTS_UPLOADED,
    VEHICLE_ORDER_STATE_ENUM.ADDRESS_INSERTED,
    VEHICLE_ORDER_STATE_ENUM.DELIVERY_METHOD_INSERTED,
    VEHICLE_ORDER_STATE_ENUM.REFUSED,
    VEHICLE_ORDER_STATE_ENUM.PROVISIONING,
    VEHICLE_ORDER_STATE_ENUM.PENDING_REVIEW,
    VEHICLE_ORDER_STATE_ENUM.REVIEWED,
    VEHICLE_ORDER_STATE_ENUM.DOCUMENTS_CONFLICT,
    VEHICLE_ORDER_STATE_ENUM.PRICE_CONFLICT,
    VEHICLE_ORDER_STATE_ENUM.PENDING_ISSUANCE,
    VEHICLE_ORDER_STATE_ENUM.ISSUED,
    VEHICLE_ORDER_STATE_ENUM.CANCELLED,
    VEHICLE_ORDER_STATE_ENUM.EXPIRED,
    VEHICLE_ORDER_STATE_ENUM.WAITING_FOR_POSTAL_CODE,
    VEHICLE_ORDER_STATE_ENUM.VERIFY_POSTAL_CODE,
  ],
  [ListOptionEnum.RENEWAL]: []
};
