export enum ErrorStatus {
  INVALID_OTP = 1089, // title : "DEVICE_INVALID_SMS_TOKEN"
  INVALID_PIN = 2001, // "title" : "AUTHENTICATION_FAILURE"
  INVALID_PIN_2 = 2008, // "title" : "AUTHENTICATION_FAILURE"
  TICKET_EXPIRED = 1100, // "title": "INVALID_TICKET",
  UNAUTHORIZED = 401,
  NOT_FOUND = 422,
  SERVICE_ERROR = 504,
  INTERNAL_SERVICE_ERROR = 500,
  INTERNET_CONNECTION = 0,
}
