export enum ResultDataStatusEnum {
  DIRECT_DEBIT_CONTRACT_ACTIVATION_FAILURE = 9208,
  SWCH_BANK_DIRECT_DEBIT_INVALID_STATUS = 5068,
  SWCH_BANK_DIRECT_DEBIT_VERIFICATION_FAILED = 5067,
  BANKPROXY_CONTRACT_ALREADY_EXISTS = 10060,
  INVALID_PARAMETER = 1054,
  DATA_PROCESSING_ERROR = 9208,
  PENDING = 0,
  ACTIVE = 1,
  FAILED = 5
}
