##
# `gzip` Compression Settings
#
#
gzip on;
gzip_disable "msie6";

gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length 256;
gzip_types
  application/atom+xml
  application/geo+json
  application/javascript
  application/x-javascript
  application/json
  application/ld+json
  application/manifest+json
  application/rdf+xml
  application/rss+xml
  application/xhtml+xml
  application/xml
  font/eot
  font/otf
  font/ttf
  image/svg+xml
  text/css
  text/javascript
  text/plain
  text/xml;
server {
  listen 80;
  server_name localhost;
  client_max_body_size 100M;

  location ^~ /digipay/api/ {
    proxy_http_version 1.1;
    proxy_pass http://gateway.app;
  }

  location /digipay/api/insurance/v1/application-forms {
  		proxy_pass http://gateway.app.svc;
  }
  ## Insurance Vehicle
  location /digipay/api/insurance/vehicle {
      proxy_pass http://gateway.app.svc;
  }

  ## Insurance Electrical equipment
  location /digipay/api/insurance/ {
      proxy_pass http://insurance-panelapi.insurance.svc;
  }

  location ~* /ngsw\.json$ {
       root /var/www/;
       try_files $uri $uri/ =404;

       # Disable caching completely
       add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
       add_header Pragma "no-cache";
       expires -1;

       # Ensure the JSON file is served with correct MIME type
       add_header Content-Type application/json;
  }

  location ~* /ngsw-worker\.js$ {
         root /var/www/;
         try_files $uri $uri/ =404;

         # Disable caching completely
         add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
         add_header Pragma "no-cache";
         expires -1;
  }

  location ~* ^/digipay/api/.+\.(png|ico|gif|jpg|jpeg|css|js|svg|woff|woff2|ttf|json|pdf)$ {
      proxy_http_version 1.1;
      proxy_pass http://gateway.app;
  }

  location ~* .(png|ico|gif|jpg|jpeg|css|js|svg|woff|woff2|ttf|json|pdf)$ {
      root /var/www/;
      try_files $uri  =404;
  }

  location /mini-app/insurance {
    alias /var/www/mini-app/insurance/;
    try_files $uri$args $uri$args/ /mini-app/insurance/index.html;
  }

  location /mini-app/ {
    root /var/www/;
    try_files $uri /index.html;
    index  index.html;
  }

  location ~* /index\.html$ {
    root /var/www/;
    try_files $uri $uri/ /index.html;
    index index.html;

    # Disable caching
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    expires -1;
  }

  location / {
    root /var/www/;
    try_files $uri $uri/ /index.html;
    index index.html;
  }
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
