export enum ENOTE_STEP_STATUS {
  INITIATED,
  IN_PROGRESS,
  READY_TO_PAYMENT,
  PAID,
  COMPLETED,
  WAITING,
  EXPIRED,
  FAILED,
  PHYSICAL_ON_BOARDED,
  PHYSICAL_GENERATED,
  PHYSICAL_UPLOADED,
  PHYSICAL_REJECTED,
}
