export enum BimehMessageType {
  SCRIPT_LOADED = 'SCRIPT_LOADED',
  URL_CHANGE = 'URL_CHANGE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  GO_TO_PAYMENT = 'GO_TO_PAYMENT',
  NAVIGATE_TO_URL = 'NAVIGATE_TO_URL',
  GO_TO_MY_POLICIES = 'GO_TO_MY_POLICIES',
  API_LOG = 'API_LOG',
}
