export enum VOLUNTEER_STATE_TYPE {
  INACTIVE_PLAN,
  RESULT,
  REGISTERED,
  PENDING,
  CARD_NOT_FOUND,
  INVALID_CELL_NUMBER,
  INVALID_BALANCE,
  LIMIT_FUND_PROVIDER,
  LIMIT_INDIVIDUAL_LEASING,
  LIMIT_ACTIVATION,
  INACTIVE_CARD,
  DEFAULT,
}
