export enum VOLUNTEER_STATES {
  ON_BOARDING = 0,
  ON_BOARDED = 1,
  PREREGISTERING = 2,
  PREREGISTERED = 3,
  REGISTERED = 4,
  REGISTRATION_FAILED = 5,
  DUPLICATE_CELL_NUMBER = 6,
  DUPLICATE_NATIONAL_ID = 7,
}
