export enum GeneralErrorTypes {
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  INTERNET_ERROR = 'INTERNET_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  ACCESS_ERROR = 'ACCESS_ERROR',
  UNAVAILABLE_SYSTEM_ERROR = 'UNAVAILABLE_SYSTEM_ERROR',
}
