#stage 1
FROM registry.mydigipay.info/cicd/generic/node-20.12.2:latest as build-step
# argument

#copy the file
WORKDIR workspace
# Copy the files
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY .npmrc ./
RUN apk add unzip git
RUN corepack enable
RUN pnpm install --frozen-lockfile
COPY . .

# Run Versioning script to write current version from ngsw-config.json to environment files
RUN node intrack-service-worker.js
RUN npx nx build dpx --configuration=staging --outputPath=dist/apps/app

#Obfuscate specific chunks (e.g., c2c lib)
RUN node obfuscate-c2c.js

# # Conditional Sentry sourcemaps command
RUN configuration=staging ./docker/sentry-sourcemap.sh ${appName}


#stage 2

FROM docker.mydigipay.info/nginx:alpine as publish
COPY --from=build-step /workspace/dist/apps/app/browser /var/www
RUN mkdir /var/www/mini-app

#Copy nginx configuration files
COPY docker/nginx/local.conf.d/local-default.conf /etc/nginx/conf.d/default.conf

#expose port 80
EXPOSE 80

#run nginx
CMD ["nginx" , "-g", "daemon off;"]
