export enum EIntrackEventName {
  HOME_PAGE_VIEW = 'w_home_page_view',
  PRICE_PAGE_VIEW = 'w_price_page_view',
  NEWS_PAGE_VIEW = 'w_news_page_view',
  NEWS_SELECT = 'w_news_select',
  FAQ_SELECT = 'w_faq_select',
  ASSET_CLASS_SELECT = 'w_asset_class_select',
  FUND_PROFILE_DETAIL = 'w_fund_prfile_detail',
  FUND_BUY_PAGE = 'w_fund_buy_page',
  PROFILE_INVESTMENT_SELECT = 'w_profile_investment_select',
  BUY_INVESTMENT_SELECT = 'w_buy_investment_select',
  NATIONAL_ID_SEND = 'w_national_id_send',
  OTP_DONE = 'w_otp_done',
  SHAHKAR_TRUE = 'w_shahkar_true',
  SHAHKAR_SERVICE_ERROR = 'w_shahkar_service_error',
  SHAHKAR_MISSMATCH = 'w_shahkar_missmatch',
  SEJAM_FALSE = 'w_sejam_false',
  SEJAM_TRUE = 'w_sejam_true',
  SEJAM_SERVICE_ERROR = 'w_sejam_service_error',
  SET_PASSWORD_DONE = 'w_set_password_done',
  PAYMENT_START = 'w_payment_start',
  PAYMENT_DONE = 'w_payment_done',
  REGISTER_CUSTOMER_IN_INVESTMENT = 'w_register_customer_in_investment',
  AGRREMENT_DONE = 'w_agrrement_done',
  TEMPORARY_DOWN = 'w_temporary_down',
}
