export enum SaleChannelEnum {
  USED_DEVICE = 'USED_DEVICE',
  BUNDLED = 'BUNDLED',
  UNBUNDLED = 'UNBUNDLED',
  PURE_BUNDLE = 'PURE_BUNDLE',
  RENEWAL = 'RENEWAL',
  SUBSCRIPTION_OFFLINE = 'SUBSCRIPTION_OFFLINE',
}
