server {
    listen	80;
    server_name localhost;
    client_max_body_size 5M;
    add_header X-SERVER W_WEBSITE;
    server_tokens off;

    location / {
        root /var/www/app/digipay-ui/browser;
        try_files $uri $uri/ /index.html;
        index  index.html;
    }

    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
