export enum PAYMENT_METHOD {
  ALLOCATION_PREPAYMENT,
  PURCHASE_PREPAYMENT,
  SUBSCRIPTION,
  NONE,
}

export const PAYMENT_METHOD_TRANSLATION = {
  [PAYMENT_METHOD.ALLOCATION_PREPAYMENT]: 'هزینه خدمات و زیرساخت',
  [PAYMENT_METHOD.PURCHASE_PREPAYMENT]: 'کسر از وام',
  [PAYMENT_METHOD.SUBSCRIPTION]: 'اشتراک دیجی‌پی',
  [PAYMENT_METHOD.NONE]: 'هیچکدام',
};
