export enum SettlementValue {
  PAID = 1,
  UPLOAD_IN_PROGRESS = 2,
  UPLOADED = 3,
  ALLOCATED = 5,
  REPAYMENT_FAILED = 6,
  INCONSISTENT = 7,
  CONFIRMED = 8,
  EXPIRED = 10,
  UNKNOWN = 12,
  ALLOCATION_FAILED = 13,
  UNDER_PAID = 14,
  KYC_VERIFIED = 15,
  REPAID = 16
}
