export const THIRD_PARTY_MOTOR_ROUTE = {
  ExInsurerMotor: 'ex-insurer-motor',
  ExInsurerMotorDate: 'ex-insurer-motor-date',
  ExInsurerMotorInfo: 'ex-insurer-motor-info',
  PriceCardList: 'price-card-list',
  Checkout: 'checkout',
  Payment: 'payment',
  GoToCheckout: 'go-to-checkout',
  GoToPayment: 'go-to-payment',
  PaymentResult: 'payment-result',
  UserInfo: 'user-info',
  UserAddress: 'user-address',
  UploadDocument: 'upload-document',
  AdditionalUploadDocument: 'additional-upload-document',
  GetPolicyMethod: 'get-policy-method',
  CompleteOrder: 'complete-order',
  OrderState: 'order-state',
  ResolveDocumentsConflict: 'resolve-documents-conflict',
  VerifyPostalCode: 'verify-postal-code',
};
