export enum VouchersRestrictionFields {
  TITLE = 'title',
  STORE_CATEGORIES = 'store.categories',
  STORE_TRACKING_CODE = 'store.trackingCode',
  STORE_DEACTIVE = 'store.state.disabled',
  EXPIRATION_DATE = 'expirationDate',
  KEYWORD = 'keyword',
}
export const StoreCategoryToDefaultVoucherImageMapper: Record<string, string> = {
  [StoreCategoryTitle.GOLD_AND_COINS]: 'jewelery.png',
  [StoreCategoryTitle.DIGITAL]: 'digital.png',
  [StoreCategoryTitle.FASHION_AND_CLOTHING]: 'fashion.png',
  [StoreCategoryTitle.SPORTS_AND_TRAVEL]: 'trip.png',
  [StoreCategoryTitle.ENTERTAINMENT_AND_TOURISM]: 'entertainment.png',
  [StoreCategoryTitle.MEDICINE_AND_TREATMENT]: 'doctor.png',
  [StoreCategoryTitle.BEAUTY_AND_HEALTH]: 'beauty.png',
  [StoreCategoryTitle.TOYS_FOR_CHILDREN_AND_BABIES]: 'kids.png',
  [StoreCategoryTitle.HOUSEHOLD_CONSUMER]: 'home-essentials.png',
  [StoreCategoryTitle.HOME_AND_KITCHEN]: 'home-and-kitchen.png',
  [StoreCategoryTitle.BUILDING_TOOLS_AND_INDUSTRIAL_EQUIPMENT]: 'tools.png',
  [StoreCategoryTitle.BOOKS_STATIONERY]: 'stationery.png',
  [StoreCategoryTitle.CARS_AND_MOTORCYCLES]: 'car.png',
  [StoreCategoryTitle.EDUCATION_AND_ENTERTAINMENT]: 'courses.png',
  [StoreCategoryTitle.SERVICES]: 'repair.png',
  [StoreCategoryTitle.RESTAURANT]: 'food.png',
  [StoreCategoryTitle.PETS]: 'pet.png',
  [StoreCategoryTitle.FLOWER_AND_PLANTS]: 'plant.png',
  [StoreCategoryTitle.BIRTHDAY_GIFTS_AND_ACCESSORIES]: 'gift.png',
  [StoreCategoryTitle.SPORT]: 'exercise.png',
  [StoreCategoryTitle.INTERNET_SERVICES]: 'internet.png',
  [StoreCategoryTitle.ONLINE_SHOP]: 'online-store.png',
};

const enum StoreCategoryTitle {
  CARS_AND_MOTORCYCLES = 'CARS_AND_MOTORCYCLES',
  GOLD_AND_COINS = 'GOLD_AND_COINS',
  DIGITAL = 'DIGITAL',
  FASHION_AND_CLOTHING = 'FASHION_AND_CLOTHING',
  TOYS_FOR_CHILDREN_AND_BABIES = 'TOYS_FOR_CHILDREN_AND_BABIES',
  HOUSEHOLD_CONSUMER = 'HOUSEHOLD_CONSUMER',
  BEAUTY_AND_HEALTH = 'BEAUTY_AND_HEALTH',
  HOME_AND_KITCHEN = 'HOME_AND_KITCHEN',
  BUILDING_TOOLS_AND_INDUSTRIAL_EQUIPMENT = 'BUILDING_TOOLS_AND_INDUSTRIAL_EQUIPMENT',
  BOOKS_STATIONERY = 'BOOKS_STATIONERY',
  SPORTS_AND_TRAVEL = 'SPORTS_AND_TRAVEL',
  MEDICINE_AND_TREATMENT = 'MEDICINE_AND_TREATMENT',
  EDUCATION_AND_ENTERTAINMENT = 'EDUCATION_AND_ENTERTAINMENT',
  SERVICES = 'SERVICES',
  ENTERTAINMENT_AND_TOURISM = 'ENTERTAINMENT_AND_TOURISM',
  PETS = 'PETS',
  FLOWER_AND_PLANTS = 'FLOWER_AND_PLANTS',
  BIRTHDAY_GIFTS_AND_ACCESSORIES = 'BIRTHDAY_GIFTS_AND_ACCESSORIES',
  RESTAURANT = 'RESTAURANT',
  SPORT = 'SPORT',
  ONLINE_SHOP = 'ONLINE_SHOP',
  INTERNET_SERVICES = 'INTERNET_SERVICES',
}
