---
stages:
  - build
  - trigger

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "master"
      when: always
    - when: never

include:
  - component: ${CI_SERVER_FQDN}/cicd/components/angular/default-standalone@$DP_CI_ANGULAR_COMPONENTS_VERSION
    inputs:
      project-name: "web-credit"

Trigger Web-Mydigipay:
  stage: trigger
  trigger:
    project: "frontend/web.mydigipay"
    branch: "$CI_COMMIT_BRANCH"
    forward:
      yaml_variables: false
  when: on_success
