import { RegistrationState as RS } from '../../../api/models/registration/states';

export enum RegistrationPages {
  WELCOME,
  RULE_SELECTION,
  OVERVIEW,
  DOCUMENT_SELECTION,
  SCORE_CALCULATION,
  FEE_PAYMENT,
  IDENTIFICATION,
  DIGITAL_SIGNATURE,
  ACCOUNT_OPENING,
  SIGNING,
}

export const RegistrationStateToPageMap: { [key: string]: number[] } = {
  [RegistrationPages.DOCUMENT_SELECTION]: [
    RS.INITIATED
  ],
  [RegistrationPages.SCORE_CALCULATION]: [
    RS.MAX_CREDIT_AMOUNT_REVISED,
    RS.ICS_REJECTED,
    RS.ICS_CELL_NUMBER_INQUIRY_REJECTED,
  ],
  [RegistrationPages.FEE_PAYMENT]: [
    RS.CREDIT_SCORE_PASSED,
    RS.VERIFY_UNKNOWN,
    RS.VERIFY_SUCCESSFUL,
    RS.CONFIRMED,
    RS.UNKNOWN_REVERSED,
    RS.REVERSED,
    RS.FAILED_EXPIRED,
    RS.EXPIRED,
  ],
  [RegistrationPages.IDENTIFICATION]: [
    RS.IDENTITY_EVALUATION,
    RS.IDENTITY_EVALUATION_SET_DETAILS,
    RS.IDENTITY_EVALUATION_SET_ADDRESS,

    RS.IDENTITY_EVALUATION_INITIATED,
    RS.BIRTH_DATE_FILLED,
    RS.INVALID_BIRTH_DATE,
    RS.OTP_VERIFIED,
    RS.OTP_FAILED,
    RS.IDENTITY_REGISTRATION_INQUIRY_COMPLETED,
    RS.IDENTITY_REGISTRATION_INQUIRY_FAILED,
    RS.IDENTITY_INFO_COMPLETED,
    RS.INVALID_IDENTITY_INFO,
    RS.OTP_VERIFICATION_FAILED,
    RS.OTP_VERIFICATION_PENDING,
    RS.OTP_VERIFICATION_SUCCESS,
    RS.OTP_VERIFICATION_INVALID_OTP,
    RS.OTP_VERIFICATION_OTP_CONFIRMED_BEFORE,
    RS.OTP_VERIFICATION_CODE_IS_EXPIRED_TRY_AGAIN,
    RS.OTP_VERIFICATION_REQUEST_IS_INVALID,
    RS.OTP_VERIFICATION_COUNT_OF_UNSUCCESSFUL_RETRY_IS_NOT_LEGAL,
    RS.OTP_VERIFICATION_SEND_OTP_MAX_RETRY_REACHED,
  ],
  [RegistrationPages.DIGITAL_SIGNATURE]: [
    RS.DIGITAL_SIGNATURE,
    RS.DIGITAL_SIGNATURE_PENDING,
    RS.DIGITAL_SIGNATURE_INITIATED,
    RS.DIGITAL_SIGNATURE_COMPLETED,
  ],
  [RegistrationPages.ACCOUNT_OPENING]: [
    RS.UPLOAD_DOCUMENTS,
    RS.OPEN_ACCOUNT,
    RS.OPEN_ACCOUNT_INQUIRY,
    RS.OPEN_ACCOUNT_SUBMITTED,
    RS.OPEN_ACCOUNT_FAILED,
    RS.DOCUMENTS_UPLOAD_COMPLETED,
    RS.OPEN_ACCOUNT_COMPLETED,
  ],
  [RegistrationPages.SIGNING]: [
    RS.CONTRACT_GENERATION,
    RS.CONTRACT_GENERATION_RESULT,
    RS.CONTRACT_SIGNING,
    RS.OPEN_ACCOUNT_SUCCEED,
    RS.DOCUMENT_GENERATION_INITIATED,
    RS.DOCUMENT_GENERATION_FAILED,
    RS.DOCUMENT_GENERATED,
    RS.DOCUMENT_SIGNED,
    RS.CREDIT_LINE,
    RS.CREDIT_LINE_UPLOAD_FILE,
    RS.CREDIT_LINE_INQUIRY,
    RS.CREDIT_LINE_INQUIRY_FAILED,
    RS.COMPLETED_CREDIT_LINE,
    RS.CREDIT_LINE_INQUIRY_REJECTED
  ]
};
