import {
  AMLAK_PROVIDER_UNAVAILIBLE_ROUTE,
  CASHOUT_ROUTE,
  CUSTOMER_DEATH_ROUTE,
  NATIONAL_ID_ROUTE,
  POSTAL_CODE_REGISTRATION_ROUTE,
  QUICK_PAYMENT,
  RECEIPT_ROUTE,
  SELECT_BANK_ACCOUNT_ROUTE,
  WALLET_BNPL_CONFIRMATION,
  WALLET_BNPL_DETAIL_ROUTE,
  WALLET_BNPL_PAYMENT_DETAIL_ROUTE,
  WALLET_BNPL_RECHARGE,
  WALLET_BNPL_REQUEST_FAILURE_ROUTE,
  WALLET_BNPL_REQUEST_ROUTE,
  WALLET_BNPL_ROUTE,
  WALLET_CASH_IN_ROUTE,
  WALLET_CASH_OUT_ROUTE,
  WALLET_CUTOFF_ROUTE,
  WALLET_DEBT_NOTICE_ROUTE,
  WALLET_FX_BNPL,
  WALLET_FX_DEPOSIT,
  WALLET_FX_WITHDRAW,
  WALLET_FX_WITHDRAW_CONFIRMATION,
  WALLET_GOLD_BNPL,
  WALLET_GOLD_DEPOSIT,
  WALLET_GOLD_WITHDRAW,
  WALLET_GOLD_WITHDRAW_CONFIRMATION,
  WALLET_MIX_BNPL,
  WALLET_TERMS_CONDITIONS_ROUTE,
  WALLET_WITHDRAW_GOLD_PENDING,
  WALLETS_ROUTE,
} from '../../../../data-access/constants/app-routes';

export const WALLET_PAGE_ROUTE_MAP: Record<string, string> = {
  page_wallet_fx_bnpl_cash_in_landing: WALLET_FX_BNPL,
  page_wallet_fx_bnpl_cash_in_confirmation: WALLET_BNPL_CONFIRMATION,
  page_wallet_gold_bnpl_cash_in_confirmation: WALLET_BNPL_CONFIRMATION,
  page_wallet_mix_bnpl_cash_in_confirmation: WALLET_BNPL_CONFIRMATION,
  page_wallet_gold_bnpl_cash_in_landing: WALLET_GOLD_BNPL,
  page_wallet_cash_in_landing: WALLET_CASH_IN_ROUTE,
  page_wallet_deposit_fx_landing: WALLET_FX_DEPOSIT,
  page_wallet_deposit_gold_landing: WALLET_GOLD_DEPOSIT,
  page_wallet_cach_out_landing: WALLET_CASH_OUT_ROUTE,
  page_wallet_withdraw_fx_landing: WALLET_FX_WITHDRAW,
  page_wallet_withdraw_fx_confirmation: WALLET_FX_WITHDRAW_CONFIRMATION,
  page_wallet_withdraw_gold_landing: WALLET_GOLD_WITHDRAW,
  page_wallet_withdraw_gold_confirmation: WALLET_GOLD_WITHDRAW_CONFIRMATION,
  page_global_sheba_number: SELECT_BANK_ACCOUNT_ROUTE,
  page_global_customer_birth_date: WALLET_BNPL_ROUTE,
  page_wallet_bnpl_receipt: WALLET_BNPL_DETAIL_ROUTE,
  page_wallet_cash_in_terms: WALLET_TERMS_CONDITIONS_ROUTE,
  page_wallet_cach_out_receipt: RECEIPT_ROUTE,
  page_wallet_withdraw_fx_receipt: RECEIPT_ROUTE,
  page_wallet_withdraw_gold_receipt: RECEIPT_ROUTE,
  page_wallet_cach_out_process: CASHOUT_ROUTE,
  page_wallet_landing: WALLETS_ROUTE,
  page_global_national_id: NATIONAL_ID_ROUTE,
  page_wallet_cash_in_cutoff_time: WALLET_CUTOFF_ROUTE,
  page_bnpl_deposit_scoring_fail: WALLET_BNPL_REQUEST_FAILURE_ROUTE,
  page_wallet_bnpl_cash_in_landing: WALLET_BNPL_REQUEST_ROUTE,
  page_wallet_bnpl_cash_in_confirmation: WALLET_BNPL_PAYMENT_DETAIL_ROUTE,
  page_wallet_customer_information: WALLET_BNPL_ROUTE,
  page_wallet_bnpl_dept_landing: WALLET_DEBT_NOTICE_ROUTE,
  page_global_customer_death: CUSTOMER_DEATH_ROUTE,
  page_postal_code_not_registered: POSTAL_CODE_REGISTRATION_ROUTE,
  page_amlak_provider_unavailable: AMLAK_PROVIDER_UNAVAILIBLE_ROUTE,
  page_wallet_mix_bnpl_cash_in_landing: WALLET_MIX_BNPL,
  page_wallet_bnpl_recharge_landing: WALLET_BNPL_RECHARGE,
  page_wallet_deposit_confirmation: QUICK_PAYMENT,
  page_wallet_withdraw_gold_pending: WALLET_WITHDRAW_GOLD_PENDING,
};
