export const STEP_TAGS: {
  [key: number]:
    | 'EMPTY_TAG'
    | 'NATIONAL_CARD_FRONT'
    | 'NATIONAL_CARD_BACK'
    | 'OWNERSHIP_DOCUMENT'
    | 'JOB_DOCUMENT'
    | 'BIRTH_CERTIFICATE'
    | 'OTHER_DOCUMENT';
} = {
  0: 'EMPTY_TAG',
  1: 'NATIONAL_CARD_FRONT',
  2: 'NATIONAL_CARD_BACK',
  3: 'OWNERSHIP_DOCUMENT',
  4: 'JOB_DOCUMENT',
  5: 'BIRTH_CERTIFICATE',
  6: 'OTHER_DOCUMENT',
};
