export const STEP_STATUSES: {
  [key: number]:
    | 'INITIATE'
    | 'INPROGRESS'
    | 'OPERATIONAL_PENDING'
    | 'OPERATIONAL_ACCEPTANCE'
    | 'OPERATIONAL_REJECTION'
    | 'COMPLETED'
    | 'FAILED';
} = {
  0: 'INITIATE',
  1: 'INPROGRESS',
  2: 'OPERATIONAL_PENDING',
  3: 'OPERATIONAL_ACCEPTANCE',
  4: 'OPERATIONAL_REJECTION',
  5: 'COMPLETED',
  6: 'FAILED',
};
