export const GA_DIRECT_DEBIT_ID = {
  HOME: {
    CANCEL_BTN_CLICK: 'DIRECT_DEBIT_HOME_CANCEL_BTN_CLICK',
    NATIONAL_CODE_TYPE: 'DIRECT_DEBIT_HOME_NATIONAL_CODE_TYPE',
    CREATE_CONTRACT_CLICK: 'DIRECT_DEBIT_HOME_CREATE_CONTRACT_CLICK',
    CANCEL_CONTRACT_CLICK: 'DIRECT_DEBIT_HOME_CANCEL_CONTRACT_CLICK',
    CONFIRM_CONTRACT_CANCELLATION_CLICK: 'DIRECT_DEBIT_HOME_CONFIRM_CONTRACT_CANCELLATION_CLICK',
    ABORT_CONTRACT_CANCELLATION_CLICK: 'DIRECT_DEBIT_HOME_ABORT_CONTRACT_CANCELLATION_CLICK'
  },
  CONTRACT: {
    SELECT_BANK_CLICK: 'DIRECT_DEBIT_CONTRACT_SELECT_BANK_CLICK',
    CONTINUE_AFTER_SELECTING_BANK_CLICK: 'DIRECT_DEBIT_CONTRACT_CONTINUE_AFTER_SELECTING_BANK_CLICK',
    CANCEL_BANK_SELECTION_CLICK: 'DIRECT_DEBIT_CONTRACT_CANCEL_BANK_SELECTION_CLICK ',
    CHANGE_DEFAULT_DURATION_CLICK: 'DIRECT_DEBIT_CONTRACT_CHANGE_DEFAULT_DURATION_CLICK',
    PICK_HIGH_USAGE_MODEL: 'DIRECT_DEBIT_CONTRACT_PICK_HIGH_USAGE_MODEL',
    PICK_LOW_USAGE_MODEL_CLICK: 'DIRECT_DEBIT_CONTRACT_PICK_LOW_USAGE_MODEL_CLICK',
    CHANGE_MINIMUM_BALANCE_TYPE: 'DIRECT_DEBIT_CONTRACT_CHANGE_MINIMUM_BALANCE_TYPE',
    CHANGE_MAXIMUM_AMOUNT_TYPE: 'DIRECT_DEBIT_CONTRACT_CHANGE_MAXIMUM_AMOUNT_TYPE ',
    CANCEL_CONTRACT_CREATION: 'DIRECT_DEBIT_CONTRACT_CANCEL_CONTRACT_CREATION',
    CONTINUE_CONTRACT_CREATION_CLICK: 'DIRECT_DEBIT_CONTRACT_CONTINUE_CONTRACT_CREATION_CLICK',
    RETURN_TO_MERCHANT_CLICK: 'DIRECT_DEBIT_CONTRACT_RETURN_TO_MERCHANT_CLICK',
  }
};
