export const GA_SUBSCRIPTION_ID = {
  MANAGEMENT: {
    ERROR_ON_LOADING_DATA_ERROR: 'SUBSCRIPTION_MANAGEMENT_ERROR_ON_LOADING_DATA_ERROR',
    CANCEL_CONTRACT_CLICK: 'SUBSCRIPTION_MANAGEMENT_CANCEL_CONTRACT_CLICK',
    CONFIRM_CONTRACT_CANCELLATION_CLICK: 'SUBSCRIPTION_MANAGEMENT_CONFIRM_CONTRACT_CANCELLATION_CLICK',
    ABORT_CONTRACT_CANCELLATION_CLICK: 'SUBSCRIPTION_MANAGEMENT_ABORT_CONTRACT_CANCELLATION_CLICK',
    SAVE_CONTRACT_CANCELLATION_CLICK: 'SUBSCRIPTION_MANAGEMENT_SAVE_CONTRACT_CANCELLATION_CLICK'
  },
  CONTRACT: {
    GROUP_SELECTION_VIEW: 'SUBSCRIPTION_CONTRACT_GROUP_SELECTION_VIEW',
    SELECT_CONTRACT_TEMPLATE: 'SUBSCRIPTION_CONTRACT_SELECT_CONTRACT_TEMPLATE',
    SHOW_MORE_GROUP_BUTTON_CLICK: 'SUBSCRIPTION_CONTRACT_SHOW_MORE_GROUP_BUTTON_CLICK',
    CANCEL_TEMPLATE_ACTIVATION_CLICK: 'SUBSCRIPTION_CONTRACT_CANCEL_TEMPLATE_ACTIVATION_CLICK',
    PROCEED_TEMPLATE_ACTIVATION_CLICK: 'SUBSCRIPTION_CONTRACT_PROCEED_TEMPLATE_ACTIVATION_CLICK',
    VIEW_T_C_CLICK: 'SUBSCRIPTION_CONTRACT_VIEW_T_C_CLICK',
    CHECK_T_C_BUTTON_CLICK: 'SUBSCRIPTION_CONTRACT_CHECK_T_C_BUTTON_CLICK',
    INSUFFICIENT_BALANCE_FOR_ACTIVATION_VIEW: 'SUBSCRIPTION_CONTRACT_INSUFFICIENT_BALANCE_FOR_ACTIVATION_VIEW',
    CANCEL_CASH_IN_CLICK: 'SUBSCRIPTION_CONTRACT_CANCEL_CASH_IN_CLICK',
    PROCEED_WITH_CASH_IN_CLICK: 'SUBSCRIPTION_CONTRACT_PROCEED_WITH_CASH_IN_CLICK',
    TYPE_OTP_TYPE: 'SUBSCRIPTION_CONTRACT_TYPE_OTP_TYPE',
    SUCCESSFUL_OTP_VIEW: 'SUBSCRIPTION_CONTRACT_SUCCESSFUL_OTP_VIEW',
    SUCCESSFUL_CASH_IN_VIEW: 'SUBSCRIPTION_CONTRACT_SUCCESSFUL_CASH_IN_VIEW',
    SUCCESSFUL_CONTRACT_ACTIVATION_VIEW: 'SUBSCRIPTION_CONTRACT_SUCCESSFUL_CONTRACT_ACTIVATION_VIEW',
    RETURN_TO_MERCHANT_CLICK: 'SUBSCRIPTION_CONTRACT_RETURN_TO_MERCHANT_CLICK',
  }
};
